server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/demodb?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: chak-demo

  jackson:
    serialization:
      fail-on-unwrapped-type-identifiers: false
      write-dates-as-timestamps: true

    ## Redis \u914D\u7F6E
  redis:
    ## Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        ## \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 0
        ## \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 8
        ## \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-active: 8
        ## \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: -1ms

#mybatis:
#  type-aliases-package: com.yabo.domain
#  mapper-locations: classpath:/com.yabo.mapper/*
#  configuration:
#    mapUnderscoreToCamelCase: true

# \u65E5\u5FD7\u914D\u7F6E
logging:
  level:
    com.yabo: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error